name: Some NodeJS
on:
  push:
    branches:
      - main
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Run Lint
        run: npm run lint
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Test code
        run: npm run test
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: npm run build
        run: echo "Deploy"
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
  Download:
    runs-on: ubuntu-latest
    needs: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: npm run build
        run: echo "Deploy"
      - name: Upload
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: A
        run: ls