name: Some NodeJS
on: [push]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Run Lint
        run: npm run lint
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Test code
        run: npm run test
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: npm run build
        run: echo "Deploy"
