name: Some NodeJS
on:
  push:
    branches:
      - main
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Run Lint
        run: npm run lint
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Test code
        run: npm run test
  Deploy:
    runs-on: ubuntu-latest
    outputs:
      script_file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci

      - name: npm run build
        run: |
          ls
          echo "Deploy"
          touch new_path
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: |
            new_path
      - name: Publish JS 
        id: publish
        run: find dist/assets/*.js -type f -execdir echo '::set-ouput name=script-file::{}' ';'
  Download:
    runs-on: ubuntu-latest
    needs: Deploy
    steps:
      - name: Upload
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: A
        run: ls
      - name: B
        run: echo "${{ needs.build.ouputs.script-file }}"